---

matrix:
  - version: [ "1.20", "1.22", "1.22-micro" ]
    os_test: [ "fedora", "centos7", "rhel7", "rhel8", "rhel9", "c9s", "rhel9-unsubscribed" ]
    test_case: [ "container" ]

  - version: [ "1.20", "1.22", "1.22-micro" ]
    os_test: [ "centos7", "rhel7" ]
    test_case: [ "openshift-3" ]

  - version: [ "1.20", "1.22", "1.22-micro" ]
    os_test: [ "rhel7", "rhel8", "rhel9" ]
    test_case: [ "openshift-4" ]

...
