---

name: Random Action
on:
  workflow_run:
    workflows: [ Gather Pull Request Metadata ]
    types:
      - completed

permissions:
  contents: read

jobs:
  download-metadata:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    outputs:
      pr-metadata: ${{ steps.Artifact.outputs.pr-metadata-json }}

    steps:
      - id: Artifact
        name: Download Artifact
        uses: redhat-plumbers-in-action/download-artifact@v1
        with:
          name: pr-metadata

  test:
    needs: [ download-metadata ]
    runs-on: ubuntu-latest

    steps:
      - uses: jamacku/random-action@devel
        with:
          pr: ${{ fromJSON(needs.download-metadata.outputs.pr-metadata).number }}
          token: ${{ secrets.GITHUB_TOKEN }}

...